parameters:

    #
    # Services
    #
    elcodi.manager.banner.class: Elcodi\Component\Banner\Services\BannerManager

    #
    # Factories
    #
    elcodi.factory.banner.class: Elcodi\Component\Banner\Factory\BannerFactory
    elcodi.factory.banner_zone.class: Elcodi\Component\Banner\Factory\BannerZoneFactory
