services:

    #
    # Factories
    #

    #
    # Factory for entity banner
    #
    elcodi.core.banner.factory.banner:
        class: %elcodi.core.banner.factory.banner.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.banner.entity.banner.class%"]]

    elcodi.factory.banner:
        alias: elcodi.core.banner.factory.banner

    #
    # Factory for entity banner_zone
    #
    elcodi.core.banner.factory.banner_zone:
        class: %elcodi.core.banner.factory.banner_zone.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.banner.entity.banner_zone.class%"]]

    elcodi.factory.banner_zone:
        alias: elcodi.core.banner.factory.banner_zone
