services:

    #
    # Factories
    #

    #
    # Factory for entity banner
    #
    elcodi.factory.banner:
        class: %elcodi.factory.banner.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.banner.entity.banner.class%"]]

    #
    # Factory for entity banner_zone
    #
    elcodi.factory.banner_zone:
        class: %elcodi.factory.banner_zone.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.banner.entity.banner_zone.class%"]]
