services:

    #
    # Form Types
    #
    elcodi.core.banner.form_types.banner:
        class: %elcodi.core.banner.form_types.banner.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_banner }

    elcodi.core.banner.form_types.bannerzone:
        class: %elcodi.core.banner.form_types.bannerzone.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_bannerzone }
