services:

    #
    # Services
    #
    elcodi.core.banner.service.banner_manager:
        class: %elcodi.core.banner.service.banner_manager.class%
        arguments:
            banner_repository: @elcodi.repository.banner
